name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: Ruiqi-Chen-0216/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ruiqi-Chen-0216
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Los_Angeles
          plugin_languages: yes
          plugin_isocalendar: yes
