name: Metrics embed

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Ruiqi-Chen-0216
          template: classic
          base: header, activity, community, repositories
          config_timezone: Asia/Shanghai
          plugin_languages: yes
          plugin_isocalendar: yes
